### ISSUE TITLE
Loading gallery urls from file

### ISSUE THREAD

**Issue by anoduck** [pingbit/imagefap_scraper#1]
I was using a different imagefap scraper, that now no longer works. This scraper works great and even has more functionality than the former script. But, this script does not allow loading gallery urls from file, I have even tried using a pathetically small amount of shell script:
<code>
cat testfile.txt | python image_scraper.py --gallery_urls -
</code>
None of the above worked. Is there a way to hack this script, or use shell code to allow the script to load from file. If you are downloading more than a handful of galleries, reading from file is nearly a must.

**Comment by pingbit** [comment]
download the scraper again, and try the following:

```
cat galleries.txt | xargs python imagefap_scraper.py -p -v --gallery_urls
```

**Comment by anoduck** [comment]
That did it. Smooth as silk.
